Add -prometheus_output to -one_shot
google/mtail pull request #580
Opened 2021-08-31 13:25 UTC by roidelapluie

This provides an easier to develop mtail programs because the Prometheus
exposition format is more concise.

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

2021-08-31 13:36 UTC, SuperQ commented on cmd/mtail/main.go
> +		}
Should this have an `} else {` to not print the json output when using `prometheusOutput`?

2021-08-31 13:37 UTC, SuperQ commented on cmd/mtail/main.go
> +		opts = append(opts, mtail.PrometheusOutput)
Maybe put this before `if *oneShot {` and set `oneShot` to true?

2021-08-31 13:40 UTC, roidelapluie commented
changed to -format

2021-08-31 14:18 UTC, SuperQ commented on cmd/mtail/main.go
> +		}
:+1:

2021-08-31 14:18 UTC, SuperQ approved these changes
LGTM

2021-09-02 08:32 UTC, jaqx0r commented
I love the idea, and thanks @SuperQ for reviewing.  If I knew no-one depended on it, I'd make this the default and remove the JSON output (which I dislike.)

2021-09-02 08:36 UTC, jaqx0r requested changes

2021-09-02 08:36 UTC, jaqx0r commented on cmd/mtail/main.go
> +	oneShotFormat = flag.String("format", "json", "Format to use with -one_shot. This is a debugging flag only, not for production use. Supported formats: json, prometheus.")
Please make the flag `one_shot_format`.

2021-09-02 09:05 UTC, roidelapluie commented on cmd/mtail/main.go
> +	oneShotFormat = flag.String("format", "json", "Format to use with -one_shot. This is a debugging flag only, not for production use. Supported formats: json, prometheus.")
Done !

2021-09-02 10:06 UTC, SuperQ commented
We could always add the new option, and flip the default in a later release with some warning.

2021-09-02 20:31 UTC, jaqx0r approved these changes

2021-09-02 20:31 UTC, merged